### ISSUE TITLE
Unresolved issues

### ISSUE THREAD

**Issue by bmontana-edu** [DRay22/COOP2018#2]
[Chapter02/U02_Ex08_Compounding.py](https://github.com/DRay22/COOP2018/commit/7c2e801acd2d1b2db895bf9eecc08110cedf952e#diff-c04c08da481156ae5071f771ed53cc7b)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Mark this issue resolved when you have fixed everything mentioned.

**Comment by DRay22** [comment]
Everything has been fixed and updated to Github.
